### PR TITLE
fix(sparkplugbpayload): avoid accidentally setting a bunch of globals

### LINKED ISSUE #73: sparkplug-payload accidentally sets a bunch of global variables
```
> require('sparkplug-payload')
{ get: [Function] }
> setValue
[Function: setValue]
> encodeTypes
[Function: encodeTypes]
```

### PR DESCRIPTION
**Pull request by jedwards1211**
fix #73

### CODE REVIEW

**Comment by wes-johnson** [comment]
In order for us to be able to accept this PR you must sign the Eclipse 'ECA'. That can be found here: https://www.eclipse.org/legal/ECA.php.

For the ECA signing to be linked to your Github account, your Github email account must match the Eclipse account you used to sign the ECA. In addition, the email associated with your Github account must be publicly visible so the signed ECA can be validated against it.

**Comment by jedwards1211** [comment]
@wes-johnson okay, done

**Comment by wes-johnson** [comment]
Almost there - Please check that each commit has the 'Signed-off-by' footer as part of the commit message. This is required per Eclipse contribution rules. This can be added by checking out the offending commit and using git commit -a -s.

**Comment by jedwards1211** [comment]
It seems those instructions need clarification because `git commit -a -s` doesn't appear to work for me

**Comment by wes-johnson** [comment]
Unable to merge without ECA - closing.

**Pull request closed without merging**
