### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jmford-engr**
Fix old-style Print statements to work with Python 3
Replace obsolete string.lowercase with string.ascii_lowercase
Tested with Python 3.8.3

### CODE REVIEW

**Comment by jmford-engr** [comment]
There still is something wrong with my use of this repo.  I thought I got rid of all the old stuff I was working on, and just the last 2 commits should be used.

**Comment by wes-johnson** [comment]
Closing - unable to merge due to unsigned ECA. Please open a new PR using an Github account with the same email address that was used to sign your ECA.

**Comment by jbrzozoski** [comment]
I think uou need to include a line at the end of your commit message like:

`Signed-off-by: John Ford <jmford94@gmail.com>`

**Comment by jmford-engr** [comment]
Thanks.  I'm an old SVN guy and I am trying to get up to speed with github.

I've made a pretty big mess of my fork and I'm going to blow it away and
re-fork tahu and go from there.  I think I understand how it all works
now.  At least the simple stuff.  :)

John

**Pull request closed without merging**
